excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://rudibudiyono.github.io
title: rudi's blog on github
tagline: A log of everyday life
description: My awesome new site
paginate: 3